# Generated by Django 4.1.3 on 2022-11-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConferenceRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("projector_availability", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("comment", models.TextField(null=True)),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercise.conferenceroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("room_id", "date")},
            },
        ),
    ]
