# Generated by Django 4.1.3 on 2022-11-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomreservation",
            old_name="room_id",
            new_name="room",
        ),
        migrations.AlterUniqueTogether(
            name="roomreservation",
            unique_together={("room", "date")},
        ),
    ]
